baseurl = "https://pet-estatistica.github.io/site/"
title = "Pet-Estatística"
theme = "hugo-universal-theme"
themesDir = "./themes/"
publishDir = "docs"
languageCode = "en-US"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "pt-br"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-66454501-4"
ignoreFiles = ["\\.R$", "\\.Rmd$", "\\.sh", "_files$", "_cache$"]

# Define the number of posts per page
paginate = 10

#-----------------------------------------------------------------------
# Main menu

[menu]

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Mural"
    weight = 3

  [[menu.main]]
      parent = "Mural"
      name = "Eventos"
      url  = "/eventos/"
      weight = 1
  
  [[menu.main]]
      parent = "Mural"
      name = "Editais"
      url  = "/editais/"
      weight = 2
      
[[menu.main]]
    name = "Projetos"
    url  = "/project/"
    weight = 2

[[menu.main]]
       name = "Integrantes"
       url  = "/people/"
       weight = 4

[[menu.main]]
    name = "Contato"
    url  = "/contact/"
    weight = 5



# [[menu.main]]
#     name = "Blog"
#     url  = "/blog/"
#     weight = 4

#-----------------------------------------------------------------------
# Top bar social links menu

# [[menu.topbar]]
#     weight = 1
#     name = "GitHub"
#     url = "https://github.com/devcows/hugo-universal-theme"
#     pre = "<i class='fa fa-2x fa-github'></i>"

# [[menu.topbar]]
#     weight = 2
#     name = "Facebook"
#     url = "http://facebook.com"
#     pre = "<i class='fa fa-2x fa-facebook'></i>"

# [[menu.topbar]]
#     weight = 3
#     name = "Twitter"
#     url = "http://twitter.com"
#     pre = "<i class='fa fa-2x fa-twitter'></i>"

#[[menu.topbar]]
#    weight = 1
#   name = "Email"
#   url = "mailto:wbonat@ufpr.br"
#   pre = "<i class='fa fa-2x fa-envelope'></i>"

#-----------------------------------------------------------------------

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"
    customCSS = ["css/custom.css"]

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "pet.estatistica.ufpr@gmail.com"

    #about_us = "<p>Curso de Especialização em</br><strong>Data Science & Big Data</strong> UFPR</p><p><img src='../img/logo.jpg' width='200px'></p>"
    copyright = "Copyright (c) 2018 - 2019, Pet-Estatística; Todos os direitos reservados."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    address = """<p><strong>Departamento de Estatística</br> Universidade Federal do Paraná</strong>
        <br>Campus III - Centro Politécnico
        <br>Rua Evaristo F. F. da Costa, Bloco PC-09
        <br>Jardim das Americas
        <br>Curitiba - PR
      </p>
      """
    latitude = "-25.4502711"
    longitude = "-49.2317922"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contato: (41) 3361 3573 ou wbonat@ufpr.br.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Depoimentos"
    subtitle = "Depoimentos de pessoas sobre Data Science & Big Data."

[params.see_more]
    enable = false
    icon = "fa fa-comments"
    title = "Dúvidas? Quer saber mais?"
    subtitle = "Preparamos um conjunto de orientações para você."
    link_url = "./faq/"
    link_text = "FAQ"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Parceiros"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Nossas matérias"
    subtitle = "Fique informado sobre Data Science, Big Data, Bussiness Inteligence e temas relacionados."
