---
output:
  pdf_document: default
  word_document: default
  html_document: 
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float: yes
header-includes: \usepackage[brazil]{babel}
                 \usepackage{amsmath}
                 \usepackage{float}
                 \usepackage{bm}
csl: ABNT_UFPR_2011.csl
bibliography: refs.bib
---

```{r, include=FALSE}

knitr::opts_chunk$set(cache = TRUE)
```

```{r, echo=FALSE, include=FALSE, results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(kableExtra)
library(readxl)
library(gridExtra)

# tabela1 <- head(base, n = 10)
# T_1 <- kableExtra::kable(tabela1, align = 'lcccccc', booktabs = TRUE) %>% 
#   kableExtra::kable_styling(latex_options = c("striped", "hold_position"))
```

\begin{center}
\textbf{UNIVERSIDADE FEDERAL DO PARANÁ}

\textbf{CURSO DE ESTATÍSTICA}

\vspace{3.5cm}

Meu Nome

\vspace{5.5cm}

\textbf{Título do Trabalho}

\vspace{9.5cm}

\textbf{CURITIBA}

2019

\end{center}

# Introdução 




# Referências
